apiVersion: api.manojakumar.online/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: 5 #AM UTC
  end: 12 #AM UTC
  replicas: 5
  deployments:
    - name: nginx
      namespace: default
